import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './StoreProvider';
import 'primereact/resources/primereact.min.css'; //106Ko
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.min.css';
import manifest from '../public/manifest.json';
import './globals.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import Tailwind from 'primereact/passthrough/tailwind';
import { MyDesignSystem } from '@/core/styles/stylesController';
// ! import './app.scss';

const inter = Inter({ subsets: ['latin'], display: 'optional' });

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
  manifest: JSON.stringify(manifest),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider value={{ unstyled: true, pt: Tailwind }}>
          <Providers>{children}</Providers>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
